// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace InvoiceNinjaClient.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class CompanyUser
    {
        /// <summary>
        /// Initializes a new instance of the CompanyUser class.
        /// </summary>
        public CompanyUser()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the CompanyUser class.
        /// </summary>
        /// <param name="permissions">The company user permissions</param>
        /// <param name="settings">The company name</param>
        /// <param name="isOwner">Determines whether the user owns this
        /// company</param>
        /// <param name="isAdmin">Determines whether the user is the admin of
        /// this company</param>
        /// <param name="isLocked">Determines whether the users access to this
        /// company has been locked</param>
        /// <param name="updatedAt">The last time the record was
        /// modified</param>
        /// <param name="deletedAt">Timestamp when the user was
        /// archived</param>
        public CompanyUser(string permissions = default(string), object settings = default(object), bool? isOwner = default(bool?), bool? isAdmin = default(bool?), bool? isLocked = default(bool?), int? updatedAt = default(int?), int? deletedAt = default(int?), Account account = default(Account), Company company = default(Company), User user = default(User), CompanyToken token = default(CompanyToken))
        {
            Permissions = permissions;
            Settings = settings;
            IsOwner = isOwner;
            IsAdmin = isAdmin;
            IsLocked = isLocked;
            UpdatedAt = updatedAt;
            DeletedAt = deletedAt;
            Account = account;
            Company = company;
            User = user;
            Token = token;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Gets or sets the company user permissions
        /// </summary>
        [JsonProperty(PropertyName = "permissions")]
        public string Permissions { get; set; }

        /// <summary>
        /// Gets or sets the company name
        /// </summary>
        [JsonProperty(PropertyName = "settings")]
        public object Settings { get; set; }

        /// <summary>
        /// Gets or sets determines whether the user owns this company
        /// </summary>
        [JsonProperty(PropertyName = "is_owner")]
        public bool? IsOwner { get; set; }

        /// <summary>
        /// Gets or sets determines whether the user is the admin of this
        /// company
        /// </summary>
        [JsonProperty(PropertyName = "is_admin")]
        public bool? IsAdmin { get; set; }

        /// <summary>
        /// Gets or sets determines whether the users access to this company
        /// has been locked
        /// </summary>
        [JsonProperty(PropertyName = "is_locked")]
        public bool? IsLocked { get; set; }

        /// <summary>
        /// Gets or sets the last time the record was modified
        /// </summary>
        [JsonProperty(PropertyName = "updated_at")]
        public int? UpdatedAt { get; set; }

        /// <summary>
        /// Gets or sets timestamp when the user was archived
        /// </summary>
        [JsonProperty(PropertyName = "deleted_at")]
        public int? DeletedAt { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "account")]
        public Account Account { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "company")]
        public Company Company { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "user")]
        public User User { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "token")]
        public CompanyToken Token { get; set; }

    }
}
