// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace InvoiceNinjaClient.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class Design
    {
        /// <summary>
        /// Initializes a new instance of the Design class.
        /// </summary>
        public Design()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the Design class.
        /// </summary>
        /// <param name="id">The design hashed id</param>
        /// <param name="name">The design name</param>
        /// <param name="designProperty">The design HTML</param>
        /// <param name="isCustom">Flag to determine if the design is a custom
        /// user design</param>
        /// <param name="isActive">Flag to determine if the design is available
        /// for use</param>
        /// <param name="isDeleted">Flag to determine if the design is
        /// deleted</param>
        /// <param name="createdAt">Timestamp</param>
        /// <param name="updatedAt">Timestamp</param>
        /// <param name="deletedAt">Timestamp</param>
        public Design(string id = default(string), string name = default(string), string designProperty = default(string), bool? isCustom = default(bool?), bool? isActive = default(bool?), bool? isDeleted = default(bool?), double? createdAt = default(double?), double? updatedAt = default(double?), double? deletedAt = default(double?))
        {
            Id = id;
            Name = name;
            DesignProperty = designProperty;
            IsCustom = isCustom;
            IsActive = isActive;
            IsDeleted = isDeleted;
            CreatedAt = createdAt;
            UpdatedAt = updatedAt;
            DeletedAt = deletedAt;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Gets or sets the design hashed id
        /// </summary>
        [JsonProperty(PropertyName = "id")]
        public string Id { get; set; }

        /// <summary>
        /// Gets or sets the design name
        /// </summary>
        [JsonProperty(PropertyName = "name")]
        public string Name { get; set; }

        /// <summary>
        /// Gets or sets the design HTML
        /// </summary>
        [JsonProperty(PropertyName = "design")]
        public string DesignProperty { get; set; }

        /// <summary>
        /// Gets or sets flag to determine if the design is a custom user
        /// design
        /// </summary>
        [JsonProperty(PropertyName = "is_custom")]
        public bool? IsCustom { get; set; }

        /// <summary>
        /// Gets or sets flag to determine if the design is available for use
        /// </summary>
        [JsonProperty(PropertyName = "is_active")]
        public bool? IsActive { get; set; }

        /// <summary>
        /// Gets or sets flag to determine if the design is deleted
        /// </summary>
        [JsonProperty(PropertyName = "is_deleted")]
        public bool? IsDeleted { get; set; }

        /// <summary>
        /// Gets or sets timestamp
        /// </summary>
        [JsonProperty(PropertyName = "created_at")]
        public double? CreatedAt { get; set; }

        /// <summary>
        /// Gets or sets timestamp
        /// </summary>
        [JsonProperty(PropertyName = "updated_at")]
        public double? UpdatedAt { get; set; }

        /// <summary>
        /// Gets or sets timestamp
        /// </summary>
        [JsonProperty(PropertyName = "deleted_at")]
        public double? DeletedAt { get; set; }

    }
}
