// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace InvoiceNinjaClient.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class Paths1329sb1apiV1TemplatespostrequestbodycontentapplicationJsonschema
    {
        /// <summary>
        /// Initializes a new instance of the
        /// Paths1329sb1apiV1TemplatespostrequestbodycontentapplicationJsonschema
        /// class.
        /// </summary>
        public Paths1329sb1apiV1TemplatespostrequestbodycontentapplicationJsonschema()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the
        /// Paths1329sb1apiV1TemplatespostrequestbodycontentapplicationJsonschema
        /// class.
        /// </summary>
        /// <param name="subject">The email template subject</param>
        /// <param name="body">The email template body</param>
        public Paths1329sb1apiV1TemplatespostrequestbodycontentapplicationJsonschema(string subject = default(string), string body = default(string))
        {
            Subject = subject;
            Body = body;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Gets or sets the email template subject
        /// </summary>
        [JsonProperty(PropertyName = "subject")]
        public string Subject { get; set; }

        /// <summary>
        /// Gets or sets the email template body
        /// </summary>
        [JsonProperty(PropertyName = "body")]
        public string Body { get; set; }

    }
}
