// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace InvoiceNinjaClient.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class Pathsrynmk0apiV1ResetPasswordpostrequestbodycontentapplicationJsonschema
    {
        /// <summary>
        /// Initializes a new instance of the
        /// Pathsrynmk0apiV1ResetPasswordpostrequestbodycontentapplicationJsonschema
        /// class.
        /// </summary>
        public Pathsrynmk0apiV1ResetPasswordpostrequestbodycontentapplicationJsonschema()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the
        /// Pathsrynmk0apiV1ResetPasswordpostrequestbodycontentapplicationJsonschema
        /// class.
        /// </summary>
        /// <param name="email">The user email address</param>
        public Pathsrynmk0apiV1ResetPasswordpostrequestbodycontentapplicationJsonschema(string email = default(string))
        {
            Email = email;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Gets or sets the user email address
        /// </summary>
        [JsonProperty(PropertyName = "email")]
        public string Email { get; set; }

    }
}
