// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace InvoiceNinjaClient.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class Paymentable
    {
        /// <summary>
        /// Initializes a new instance of the Paymentable class.
        /// </summary>
        public Paymentable()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the Paymentable class.
        /// </summary>
        /// <param name="id">The paymentable hashed id</param>
        /// <param name="invoiceId">The invoice hashed id</param>
        /// <param name="creditId">The credit hashed id</param>
        /// <param name="refunded">______</param>
        /// <param name="amount">______</param>
        /// <param name="updatedAt">Timestamp</param>
        /// <param name="createdAt">Timestamp</param>
        public Paymentable(string id = default(string), string invoiceId = default(string), string creditId = default(string), double? refunded = default(double?), double? amount = default(double?), double? updatedAt = default(double?), double? createdAt = default(double?))
        {
            Id = id;
            InvoiceId = invoiceId;
            CreditId = creditId;
            Refunded = refunded;
            Amount = amount;
            UpdatedAt = updatedAt;
            CreatedAt = createdAt;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Gets or sets the paymentable hashed id
        /// </summary>
        [JsonProperty(PropertyName = "id")]
        public string Id { get; set; }

        /// <summary>
        /// Gets or sets the invoice hashed id
        /// </summary>
        [JsonProperty(PropertyName = "invoice_id")]
        public string InvoiceId { get; set; }

        /// <summary>
        /// Gets or sets the credit hashed id
        /// </summary>
        [JsonProperty(PropertyName = "credit_id")]
        public string CreditId { get; set; }

        /// <summary>
        /// Gets or sets ______
        /// </summary>
        [JsonProperty(PropertyName = "refunded")]
        public double? Refunded { get; set; }

        /// <summary>
        /// Gets or sets ______
        /// </summary>
        [JsonProperty(PropertyName = "amount")]
        public double? Amount { get; set; }

        /// <summary>
        /// Gets or sets timestamp
        /// </summary>
        [JsonProperty(PropertyName = "updated_at")]
        public double? UpdatedAt { get; set; }

        /// <summary>
        /// Gets or sets timestamp
        /// </summary>
        [JsonProperty(PropertyName = "created_at")]
        public double? CreatedAt { get; set; }

    }
}
