// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace InvoiceNinjaClient.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class Template
    {
        /// <summary>
        /// Initializes a new instance of the Template class.
        /// </summary>
        public Template()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the Template class.
        /// </summary>
        /// <param name="html">The template HTML</param>
        public Template(string html = default(string))
        {
            Html = html;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Gets or sets the template HTML
        /// </summary>
        [JsonProperty(PropertyName = "html")]
        public string Html { get; set; }

    }
}
