// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace InvoiceNinjaClient.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class ValidationError
    {
        /// <summary>
        /// Initializes a new instance of the ValidationError class.
        /// </summary>
        public ValidationError()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the ValidationError class.
        /// </summary>
        /// <param name="message">The error message</param>
        public ValidationError(string message = default(string), ValidationErrorErrors errors = default(ValidationErrorErrors))
        {
            Message = message;
            Errors = errors;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Gets or sets the error message
        /// </summary>
        [JsonProperty(PropertyName = "message")]
        public string Message { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "errors")]
        public ValidationErrorErrors Errors { get; set; }

    }
}
