// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace InvoiceNinjaClient.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    public partial class Vendor
    {
        /// <summary>
        /// Initializes a new instance of the Vendor class.
        /// </summary>
        public Vendor()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the Vendor class.
        /// </summary>
        /// <param name="id">_________</param>
        /// <param name="userId">__________</param>
        /// <param name="assignedUserId">__________</param>
        /// <param name="companyId">________</param>
        /// <param name="clientId">________</param>
        /// <param name="name">________</param>
        /// <param name="website">________</param>
        /// <param name="privateNotes">________</param>
        /// <param name="industryId">________</param>
        /// <param name="sizeId">________</param>
        /// <param name="address1">________</param>
        /// <param name="address2">________</param>
        /// <param name="city">________</param>
        /// <param name="state">________</param>
        /// <param name="postalCode">________</param>
        /// <param name="workPhone">The client phone number</param>
        /// <param name="countryId">________</param>
        /// <param name="currencyId">________</param>
        /// <param name="customValue1">________</param>
        /// <param name="customValue2">________</param>
        /// <param name="customValue3">________</param>
        /// <param name="customValue4">________</param>
        /// <param name="vatNumber">________</param>
        /// <param name="idNumber">________</param>
        /// <param name="isDeleted">________</param>
        /// <param name="lastLogin">Timestamp</param>
        /// <param name="createdAt">Timestamp</param>
        /// <param name="updatedAt">Timestamp</param>
        public Vendor(string id = default(string), string userId = default(string), string assignedUserId = default(string), string companyId = default(string), string clientId = default(string), IList<VendorContact> contacts = default(IList<VendorContact>), string name = default(string), string website = default(string), string privateNotes = default(string), string industryId = default(string), string sizeId = default(string), string address1 = default(string), string address2 = default(string), string city = default(string), string state = default(string), string postalCode = default(string), string workPhone = default(string), string countryId = default(string), string currencyId = default(string), string customValue1 = default(string), string customValue2 = default(string), string customValue3 = default(string), string customValue4 = default(string), string vatNumber = default(string), string idNumber = default(string), bool? isDeleted = default(bool?), double? lastLogin = default(double?), double? createdAt = default(double?), double? updatedAt = default(double?), CompanySettings settings = default(CompanySettings))
        {
            Id = id;
            UserId = userId;
            AssignedUserId = assignedUserId;
            CompanyId = companyId;
            ClientId = clientId;
            Contacts = contacts;
            Name = name;
            Website = website;
            PrivateNotes = privateNotes;
            IndustryId = industryId;
            SizeId = sizeId;
            Address1 = address1;
            Address2 = address2;
            City = city;
            State = state;
            PostalCode = postalCode;
            WorkPhone = workPhone;
            CountryId = countryId;
            CurrencyId = currencyId;
            CustomValue1 = customValue1;
            CustomValue2 = customValue2;
            CustomValue3 = customValue3;
            CustomValue4 = customValue4;
            VatNumber = vatNumber;
            IdNumber = idNumber;
            IsDeleted = isDeleted;
            LastLogin = lastLogin;
            CreatedAt = createdAt;
            UpdatedAt = updatedAt;
            Settings = settings;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Gets or sets _________
        /// </summary>
        [JsonProperty(PropertyName = "id")]
        public string Id { get; set; }

        /// <summary>
        /// Gets or sets __________
        /// </summary>
        [JsonProperty(PropertyName = "user_id")]
        public string UserId { get; set; }

        /// <summary>
        /// Gets or sets __________
        /// </summary>
        [JsonProperty(PropertyName = "assigned_user_id")]
        public string AssignedUserId { get; set; }

        /// <summary>
        /// Gets or sets ________
        /// </summary>
        [JsonProperty(PropertyName = "company_id")]
        public string CompanyId { get; set; }

        /// <summary>
        /// Gets or sets ________
        /// </summary>
        [JsonProperty(PropertyName = "client_id")]
        public string ClientId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "contacts")]
        public IList<VendorContact> Contacts { get; set; }

        /// <summary>
        /// Gets or sets ________
        /// </summary>
        [JsonProperty(PropertyName = "name")]
        public string Name { get; set; }

        /// <summary>
        /// Gets or sets ________
        /// </summary>
        [JsonProperty(PropertyName = "website")]
        public string Website { get; set; }

        /// <summary>
        /// Gets or sets ________
        /// </summary>
        [JsonProperty(PropertyName = "private_notes")]
        public string PrivateNotes { get; set; }

        /// <summary>
        /// Gets or sets ________
        /// </summary>
        [JsonProperty(PropertyName = "industry_id")]
        public string IndustryId { get; set; }

        /// <summary>
        /// Gets or sets ________
        /// </summary>
        [JsonProperty(PropertyName = "size_id")]
        public string SizeId { get; set; }

        /// <summary>
        /// Gets or sets ________
        /// </summary>
        [JsonProperty(PropertyName = "address1")]
        public string Address1 { get; set; }

        /// <summary>
        /// Gets or sets ________
        /// </summary>
        [JsonProperty(PropertyName = "address2")]
        public string Address2 { get; set; }

        /// <summary>
        /// Gets or sets ________
        /// </summary>
        [JsonProperty(PropertyName = "city")]
        public string City { get; set; }

        /// <summary>
        /// Gets or sets ________
        /// </summary>
        [JsonProperty(PropertyName = "state")]
        public string State { get; set; }

        /// <summary>
        /// Gets or sets ________
        /// </summary>
        [JsonProperty(PropertyName = "postal_code")]
        public string PostalCode { get; set; }

        /// <summary>
        /// Gets or sets the client phone number
        /// </summary>
        [JsonProperty(PropertyName = "work_phone")]
        public string WorkPhone { get; set; }

        /// <summary>
        /// Gets or sets ________
        /// </summary>
        [JsonProperty(PropertyName = "country_id")]
        public string CountryId { get; set; }

        /// <summary>
        /// Gets or sets ________
        /// </summary>
        [JsonProperty(PropertyName = "currency_id")]
        public string CurrencyId { get; set; }

        /// <summary>
        /// Gets or sets ________
        /// </summary>
        [JsonProperty(PropertyName = "custom_value1")]
        public string CustomValue1 { get; set; }

        /// <summary>
        /// Gets or sets ________
        /// </summary>
        [JsonProperty(PropertyName = "custom_value2")]
        public string CustomValue2 { get; set; }

        /// <summary>
        /// Gets or sets ________
        /// </summary>
        [JsonProperty(PropertyName = "custom_value3")]
        public string CustomValue3 { get; set; }

        /// <summary>
        /// Gets or sets ________
        /// </summary>
        [JsonProperty(PropertyName = "custom_value4")]
        public string CustomValue4 { get; set; }

        /// <summary>
        /// Gets or sets ________
        /// </summary>
        [JsonProperty(PropertyName = "vat_number")]
        public string VatNumber { get; set; }

        /// <summary>
        /// Gets or sets ________
        /// </summary>
        [JsonProperty(PropertyName = "id_number")]
        public string IdNumber { get; set; }

        /// <summary>
        /// Gets or sets ________
        /// </summary>
        [JsonProperty(PropertyName = "is_deleted")]
        public bool? IsDeleted { get; set; }

        /// <summary>
        /// Gets or sets timestamp
        /// </summary>
        [JsonProperty(PropertyName = "last_login")]
        public double? LastLogin { get; set; }

        /// <summary>
        /// Gets or sets timestamp
        /// </summary>
        [JsonProperty(PropertyName = "created_at")]
        public double? CreatedAt { get; set; }

        /// <summary>
        /// Gets or sets timestamp
        /// </summary>
        [JsonProperty(PropertyName = "updated_at")]
        public double? UpdatedAt { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "settings")]
        public CompanySettings Settings { get; set; }

    }
}
