// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace InvoiceNinjaClient
{
    using Models;
    using System.Threading;
    using System.Threading.Tasks;

    /// <summary>
    /// Extension methods for Reset.
    /// </summary>
    public static partial class ResetExtensions
    {
            /// <summary>
            /// Attempts to reset the users password
            /// </summary>
            /// <remarks>
            /// Resets a users email password
            /// </remarks>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='body'>
            /// Password reset email
            /// </param>
            public static object Password(this IReset operations, Pathsrynmk0apiV1ResetPasswordpostrequestbodycontentapplicationJsonschema body)
            {
                return operations.PasswordAsync(body).GetAwaiter().GetResult();
            }

            /// <summary>
            /// Attempts to reset the users password
            /// </summary>
            /// <remarks>
            /// Resets a users email password
            /// </remarks>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='body'>
            /// Password reset email
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async Task<object> PasswordAsync(this IReset operations, Pathsrynmk0apiV1ResetPasswordpostrequestbodycontentapplicationJsonschema body, CancellationToken cancellationToken = default(CancellationToken))
            {
                using (var _result = await operations.PasswordWithHttpMessagesAsync(body, null, cancellationToken).ConfigureAwait(false))
                {
                    return _result.Body;
                }
            }

    }
}
